class Global {
  static List<Map<String,dynamic>> Delhi = [
    {
      'title' : 'Delhi',
      'image' : 'https://img.static-af.com/images/meta/IDname/CITY-DEL-1?aspect_ratio=1:1&max_width=1280',
      'name1' :  'lal Killo',
      'image1' : 'http://i2.wp.com/www.nomadicfoot.com/wp-content/uploads/2015/10/Red-fort-Delhi.jpg',
      'name2' :  'India Gate',
      'image2' : 'https://www.visittnt.com/blog/wp-content/uploads/2018/07/India-Gate.jpg',
      'name3' :  'Rashtrapati Bhawan',
      'image3' : 'https://www.visittnt.com/blog/wp-content/uploads/2018/07/Rashtrapati-Bhawan-1-1024x396.jpg',
      'name4' :  'Qutub Minar',
      'image4' : 'https://www.visittnt.com/blog/wp-content/uploads/2018/07/qutub-minar-delhi-1024x768.jpg',
      'name5' :  'Jantar Mantar',
      'image5' : 'https://www.visittnt.com/blog/wp-content/uploads/2018/07/jantar-mantar.jpg',
      'name6' :  'Humayun’s Tomb',
      'image6' : 'https://www.visittnt.com/blog/wp-content/uploads/2016/07/Humanyuns-Tomb-Delhi-1024x640.jpg',
    },
  ];
  static List<Map<String,dynamic>> Madurai = [
    {
      'title' : 'Madurai',
      'image' : 'https://tse3.mm.bing.net/th?id=OIP.da1jeSkG7trE3UU9cLfTTwHaHa&pid=Api&P=0',
      'name1' :  'Madurai Meenakshi Amman Temple',
      'image1' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/71/bf/0e/madurai-meenakshi-temple.jpg?w=500&h=400&s=1',
      'name2' :  'Gandhi Memorial Museum',
      'image2' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/7e/8a/77/glowny-budynek.jpg?w=500&h=400&s=1',
      'name3' :  'Alagarkoil Temple and Shrine',
      'image3' : 'https://tse4.mm.bing.net/th?id=OIP.Ys6jd0KQ6C6IV5DkBtHA0wHaJ4&pid=Api&P=0',
      'name4' :  'Aayiram Kaal Mandapam',
      'image4' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/97/b1/37/aayiram-kaal-mandapam.jpg?w=500&h=-1&s=1',
      'name5' :  'Koodal Azhagar Temple',
      'image5' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/02/47/b2/the-sanctum-gopuram-detail.jpg?w=500&h=400&s=1',
      'name6' :  'Pazhamudhir Solai',
      'image6' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/be/21/83/pazhamudhir-solai.jpg?w=500&h=400&s=1',
    },
  ];
  static List<Map<String,dynamic>> Jaipur = [
    {
      'title' : 'Jaipur',
      'image' : 'https://www.touropia.com/gfx/b/2018/07/jaipur.jpg',
      'name1' :  'Amber Fort',
      'image1' : 'https://jaipurtourism.co.in/images/places-to-visit/header/amber-amer-fort-jaipur-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name2' :  'Jaigarh Fort',
      'image2' : 'https://jaipurtourism.co.in/images/places-to-visit/header/jaigarh-fort-jaipur-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name3' :  'Nahargarh Fort',
      'image3' : 'https://jaipurtourism.co.in/images/places-to-visit/header/nahargarh-fort-jaipur-entry-fee-timings-holidays-reviews-header.jpg',
      'name4' :  'Jantar Mantar',
      'image4' : 'https://jaipurtourism.co.in/images/places-to-visit/header/jantar-mantar-jaipur-entry-fee-timings-holidays-reviews-header.jpg',
      'name5' :  'City Palace',
      'image5' : 'https://jaipurtourism.co.in/images/places-to-visit/header/city-palace-jaipur-entry-fee-timings-holidays-reviews-header.jpg',
      'name6' :  'Hawa Mahal',
      'image6' : 'https://jaipurtourism.co.in/images/places-to-visit/header/hawa-mahal-jaipur-entry-fee-timings-holidays-reviews-header.jpg',
    },
  ];
  static List<Map<String,dynamic>> Mumbai = [
    {
      'title' : 'Mumbai',
      'image' : 'https://www.touropia.com/gfx/b/2018/07/mumbai.jpg',
      'name1' :  'Nariman Point',
      'image1' : 'https://mumbaitourism.travel/images/places-to-visit/headers/nariman-point-mumbai-indian-tourim-entry-fee-timings-holidays-reviews-header.jpg',
      'name2' :  'Gateway of India',
      'image2' : 'https://mumbaitourism.travel/images/places-to-visit/headers/gateway-of-india-mumbai-indian-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name3' :  'Flora Fountain',
      'image3' : 'https://mumbaitourism.travel/images/places-to-visit/headers/flora-fountain-mumbai-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name4' :  'Jehangir Art Gallery',
      'image4' : 'https://mumbaitourism.travel/images/places-to-visit/headers/jehangir-art-gallery-mumbai-indian-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name5' :  'Marine Drive',
      'image5' : 'https://mumbaitourism.travel/images/places-to-visit/headers/marine-drive-mumbai-indian-tourism-entry-fee-timings-holidays-reviews-header.jpg',
      'name6' :  'Rajabai Clock Tower',
      'image6' : 'https://mumbaitourism.travel/images/places-to-visit/headers/rajabai-clock-tower-mumbai-tourism-entry-fee-timings-holidays-reviews-header.jpg',
    },
  ];
  static List<Map<String,dynamic>> Agra = [
    {
      'title' : 'Agra',
      'image' : 'https://www.touropia.com/gfx/b/2018/07/agra.jpg',
      'name1' :  'Taj Mahal',
      'image1' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/9a/30/d6/agra.jpg?w=500&h=400&s=1',
      'name2' :  'Agra Fort',
      'image2' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/01/08/32/agra-fort.jpg?w=500&h=400&s=1',
      'name3' :  'Tomb of Itimad-ud-Daulah',
      'image3' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/1b/13/cf/20190114-120443-largejpg.jpg?w=500&h=-1&s=1',
      'name4' :  'Wildlife SOS',
      'image4' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/c8/87/e4/wildlife-sos.jpg?w=500&h=400&s=1',
      'name5' :  'Mother Teresa Missionaries of Charity',
      'image5' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/c0/4e/dc/mother-teresa-s-missionaries.jpg?w=500&h=400&s=1',
      'name6' :  'Jama Masjid',
      'image6' : 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/b9/88/bc/photo4jpg.jpg?w=500&h=-1&s=1',
    },
  ];
  static List<Map<String,dynamic>> Bangalore = [
    {
      'title' : 'Bangalore',
      'image' : 'https://www.touropia.com/gfx/b/2018/07/bangalore.jpg',
      'name1' :  'Bangalore Palace',
      'image1' : 'https://assets.traveltriangle.com/blog/wp-content/uploads/2020/02/Bangalore-Palace_14th-feb.jpg',
      'name2' :  'Tipu Sultan’s Summer Palace',
      'image2' : 'https://img.traveltriangle.com/blog/wp-content/uploads/2020/02/Tipu-Sultan%E2%80%99s-Summer-Palace_14th-feb.jpg',
      'name3' :  'Lal Bagh Botanical Gardens',
      'image3' : 'https://assets.traveltriangle.com/blog/wp-content/uploads/2020/02/Lal-Bagh-Botanical-Gardens_14th-feb.jpg',
      'name4' :  'Nandi Hills',
      'image4' : 'https://assets.traveltriangle.com/blog/wp-content/uploads/2020/02/Nandi-Hills_14th-feb.jpg',
      'name5' :  'Cubbon Park',
      'image5' : 'https://assets.traveltriangle.com/blog/wp-content/uploads/2020/02/Cubbon-Park_14th-feb.jpg',
      'name6' :  'National Gallery Of Modern Art',
      'image6' : 'https://assets.traveltriangle.com/blog/wp-content/uploads/2020/02/National-Gallery-of-Modern-Art_14th-feb1.jpg',
    },
  ];
}